### ISSUE TITLE
deriveKey() function call missing from base provider

### ISSUE THREAD

**Issue by tplooker** [PeculiarVentures/webcrypto-core#23]
Hi is there any plan to support or are you will to accept a PR that adds using the [deriveKey()](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey) api, in the core [provider](https://github.com/PeculiarVentures/webcrypto-core/blob/master/src/provider.ts)?

**Comment by microshine** [comment]
Provider implements [deriveBits](https://github.com/PeculiarVentures/webcrypto-core/blob/master/src/provider.ts#L124) function. I think it's enough for the key derivation.

`webcrypto-core` implements [deriveKey](https://github.com/PeculiarVentures/webcrypto-core/blob/master/src/subtle.ts#L107-L122) in `SubtleCrypto` class.
```
deriveKey
  - derive bits
  - import key
```

Does it work for you? Why do you want `deriveKey` in the `Provider` class?

**Comment by tplooker** [comment]
Hi, in general we are interested in seeing if we can expand support in this library for X25519/Curve25519 for DH and ed25519 for EDDSA. Most of the operations are relatively straightforward to implement.

[Draft EDDSA implementation](https://github.com/tplooker/webcrypto-core/tree/tl/add-eddsa)

We would also like to support a derive key operation that converts a ed25519 from an x25519 hence the interest in the derive key operation.

**Comment by microshine** [comment]
`webcrypto-core` is base project which doesn't implement crypto mechanisms. I'm using that project for the arguments checking only. 

See [NodeJS WebCrypto](https://github.com/PeculiarVentures/webcrypto) and (Browser WebCrypto)(https://github.com/PeculiarVentures/webcrypto-liner) implementations

> We would also like to support a derive key operation that converts a ed25519 from an x25519 hence the interest in the derive key operation

I'm not sure this is a good idea. You cant convert ECDSA to ECDH without `exportKey` and `importKey` functions. Use standard operations to implement this conversion.

What about `deriveKey`, as I told before you must implement `deriveBits` function. After that, you can start to use `deriveKey` from the SubtleCrypto class (eg [ECDH key derivation](https://github.com/PeculiarVentures/webcrypto/blob/master/src/mechs/ec/ec_dh.ts#L37-L40)).

**Comment by tplooker** [comment]
Hi, I realize this is just the input validation layer however it must support validation of the parameters for EDDSA and ECDH with X25519. I will review the example you have linked. Would you accept a PR for an addition of the [this](https://github.com/PeculiarVentures/webcrypto-core/compare/master...tplooker:tl/add-eddsa)?

**Comment by rmhrisk** [comment]
We are interested in supporting these however we do want to make sure we do so in a way that’s architecture consistent.

**Comment by microshine** [comment]
`@peculiar/webcrypto@1.1.6`  supports those mechanisms
https://github.com/PeculiarVentures/webcrypto/pull/25
