### ISSUE TITLE
checkDeriveBits: length is not multiple of 8

### ISSUE THREAD

**Issue by j-berman** [PeculiarVentures/webcrypto-core#31]
Not a huge deal, but providing an HMAC key length is supposed to be optional. The API relies on the hash algorithm provided to determine the length of the key, but the length can be overridden. See expected usage [here](https://github.com/diafygi/webcrypto-examples#hmac---importkey).

When I don't provide a length when trying to derive an HMAC key from an HKDF key, `webcrypto-core` throws with `OperationError: length: Is not multiple of 8`

**Comment by microshine** [comment]
@j-berman I fixed it (by default it sets 512bits as browsers do) and published the new version `v1.1.10`
