### ISSUE TITLE
"Method is not supported" error does not make sense

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/webcrypto-core#5]
We return "Method is not supported" is not a good error for the case of an unsupported algorithm.

We should return "Unsupported Algorithm : {OID}" in this case.

**Comment by microshine** [comment]
All Subtle methods return `AlgorithmError.UNSUPPORTED_ALGORITHM`

```typescript
public static UNSUPPORTED_ALGORITHM = "Algorithm '%1' is not supported";
```

`Method is not supported` is returned from `BaseCrypto`, which is abstract class for Subtle interface implementations
