### ISSUE TITLE
Align webcrypto-core with Web Cryptography API specification

### ISSUE THREAD

**Issue by YuryStrozhevsky** [PeculiarVentures/webcrypto-core#6]
At the moment seems wecrypto-core not fully aligned with Web Crypto API specification, at least in part of handling AES-CBC parameters. 

Initially my problem was that during "crypto.decrypt({ AES-CBC })" I had error:
```
Algorithm has got wrong type for paramter 'iv'. Must be ArrayBufferView.
```
After checking [Web Crypto API description for AesCbcParams](https://www.w3.org/TR/WebCryptoAPI/#dfn-AesCbcParams) I found that type for the "iv" is "BufferSource". The "BufferSource" type is defined in [WebIDL specification](https://www.w3.org/TR/WebIDL-1/#common-BufferSource):
```
typedef (ArrayBufferView or ArrayBuffer) BufferSource;
```
So, in fact the "iv" parameter could be ArrayBufferView or pure ArrayBuffer, does not matter. 

I did not check other places in webcrypto-core/webcrypto-liner for such "specification alignment issues" - I do expect you could do this yourself. At the moment I need a fix for at least correct type checking for "iv" parameter.

**Comment by microshine** [comment]
I published `webcrypto-core` and `webcrypto-liner`. Could you close issue if it works for you?
